# Generated by Django 2.1.8 on 2019-07-02 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
